### ISSUE TITLE
Simple 3D objects

### ISSUE THREAD

**Issue by AndrewTheWild** [AlexNek/BabylonBlazor#3]
Can we create simple 3d objects such as: sphere , cube?

**Comment by AlexNek** [comment]
You can create all what can create with Babylon.js 
https://playground.babylonjs.com/
https://www.tutorialspoint.com/babylonjs/babylonjs_basic_elements.htm
I want to show the way of using JS from blazor.
When I have free time, I'll try to write more samples. Try to describe your needs.

**Comment by AndrewTheWild** [comment]
I want to create custom scene with a few objects cube , sphere and other.
I try to understand how work you`re library

**Comment by AndrewTheWild** [comment]
You described on readme about custome scene creator , but used own 
![image](https://user-images.githubusercontent.com/57155452/147610598-477e3977-dd8f-42f5-8e20-98fce2bf4a31.png)
Can you give more explain how does It use?

**Comment by AlexNek** [comment]
I'll do it later, maybe at the weekend. Sorry, but I don't have much time during the work week.

**Comment by AndrewTheWild** [comment]
Don't worry ) All good) I understood
Do you plan to support library in future?

**Comment by AndrewTheWild** [comment]
Okay , I'll be to wait response from you

**Comment by AlexNek** [comment]
You can check it. Sample project extended. Box and torus added to library.
I must correct my previous answer:
You can create any Babylon.js object as long as it is implemented over babylonInterop.js. So that mean you can use custom drawing over unchanged library with predefined objects/operations/settins only. In case of no implementation you need to build you own library release.

**Comment by AlexNek** [comment]
>Do you plan to support library in future?
As long as nobody interested for the library - I have no plans to improve it. I don't need 3D engine now.
If some person want to use it and need something new - there no problem to extend the library in my "free time".

**Comment by AndrewTheWild** [comment]
Thank you)
Will investigate
